[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rtd"
version = "0.1.6"
description = "Short description here"
authors = [{name="Your Name", email="you@example.com"}]
license = {text = "MIT"}
dependencies = [
    "torch"
]
readme = "README.md"
requires-python = ">=3.8"

[project.optional-dependencies]
dev = [
  "pytest>=7.2,<8.0",
  # you can add extra test-related tools here:
  # "pytest-cov",
  # "hypothesis",
  # "flake8",
]



[tool.setuptools.packages.find]
where = ["src"]
