name: Publish to PyPI on Release

on:
  push:
    branches:
      - master

jobs:
  # Call the reusable workflow first
  build:
    uses: ./.github/workflows/python-package.yml
    with:
      artifact-name: tensor-container-nightly

  # This job runs after the reusable workflow is complete
  publish-to-testpypi:
    name: Publish to TestPyPi
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/tensor-container-nightly

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
